### ISSUE TITLE
A small suggestion

### ISSUE THREAD

**Issue by BoosterCore** [GreenLandisaLie/AuraSR-ComfyUI#10]
Is it possible to modify the code so that I can customize the model path of AuraSR in the extra_model_paths.yaml document?
I think this will allow multiple copies of ComfyUI to share models, avoiding repeated downloads of models and taking up a lot of disk space.
In addition, with more and more plugins nowadays, various dependency conflicts are also very frequent, so it is very necessary to use multiple copies of Comfy UI.

**Comment by GreenLandisaLie** [comment]
Not a bad idea. 
But the best way I envision its implementation is not yet possible (I think). I imagine it like this: 

ComfyUI Manager > Node-Specific Global Settings (shows a list of installed nodes with support for such settings) > Node Global Settings Page

Until something like that is possible any other alternative would feel like a 'workaround' - as I don't intend to add an extra in-node option for that.

However, none of that is absolutely necessary for this specific issue if you are on Windows. 

I'm personally using junctions and symlinks for this very purpose. 
A symlink is almost like a FILE shortcut that re-directs its execution to the real file location and thus works as though its the actual file when (most) programs load them.
A junction is pretty much the same but for an entire DIRECTORY/FOLDER.

Example symlink creation (cmd):
```
mklink "C:\SD\ComfyUI\models\Aura-SR\AuraSR_v1.safetensors" "D:\AI\Upscalers\AuraSR\AuraSR_v1.safetensors"
mklink "C:\SD\ComfyUI\models\Aura-SR\AuraSR_v1.json" "D:\AI\Upscalers\AuraSR\AuraSR_v1.json"
```
Example junction:
`mklink /J "C:\SD\ComfyUI\models\Aura-SR" "D:\AI\Upscalers\AuraSR"`

When creating symlinks/junctions you need to make sure the location of the symlink/junction does not exist - otherwise they won't be created. So, as per the junction example above - you would need to fist delete the "C:\SD\ComfyUI\models\Aura-SR" folder (if it exists) before creating the junction.

**Comment by BoosterCore** [comment]
OK, thank you very much for your reply. It is very inspiring. I didn't realize that I could use junctions and symlinks to solve this problem. Thank you.

**Comment by BoosterCore** [comment]
However, based on what you mentioned, "When creating symlinks/junctions you need to make sure the location of the symlink/junction does not exist - otherwise they won't be created." Does that mean that it will be troublesome if you want to have multiple copies of ComfyUI point to the same model directory at the same time?

**Comment by GreenLandisaLie** [comment]
You can have as many junctions/symlinks point to the same directories/files as you want. Its just that the location of the 'shorcut' (junction/symlink) itself must not exist when you use the command to create them - for the same reason you cannot have 2 folders or 2 files with the exact same name on the same location on Windows.

On a side note,

I can't test it right now but after looking at the 'extra_model_paths.yaml.example' file, it seems that for your use case (multiple ComfyUI installs) you could just set it to use the 'comfyui:' (template) with base_path: pointing to your 'main' ComfyUI install.

Ex:

```
comfyui:
     base_path: My_Main_ComfyUI_Install_Full_Path
     checkpoints: models/checkpoints/
     clip: models/clip/
     clip_vision: models/clip_vision/
     configs: models/configs/
     controlnet: models/controlnet/
     embeddings: models/embeddings/
     loras: models/loras/
     upscale_models: models/upscale_models/
     vae: models/vae/
```

I'm not sure if that would work or cause conflicts with custom nodes across different installs though, but junctions do work.

**Comment by BoosterCore** [comment]
Thank you very much. According to my test, for the document extra_model_paths.yaml, only the subdirectories included in its template can work. Any subdirectories generated by other plug-ins cannot be recognized even if they are manually added. This is the original reason why I made this suggestion.
In any case, thank you very much for your answer, which is very inspiring.

**Comment by GreenLandisaLie** [comment]
You might not need it anymore but I've added the ability to do what you asked like so (case sensitive):

```
somethingHere:
	
	aura-sr: your/path/to/aurasrFolder
```

**Comment by BoosterCore** [comment]
So exciting! Thank you so much!
Already tested and works perfectly!
