### ISSUE TITLE
something wrong, Can't  upscale now

### ISSUE THREAD

**Issue by RaySteve312** [GreenLandisaLie/AuraSR-ComfyUI#14]
don't know what happens.It takes an hour already.
![屏幕截图 2024-08-05 012947](https://github.com/user-attachments/assets/94b8222b-5281-4832-8007-b4719a152dbd)

**Comment by RaySteve312** [comment]
It worked on August 3rd

**Comment by GreenLandisaLie** [comment]
I haven't updated the node since 3 days ago or so, so if it was working yesterday than the problem probably lies in the input image or settings.

Are you passing a batch of images or a single image?
What's the resolution of the image(s) that's causing the issue (when the node receives it) ?
What Aura model are you using (v1 or v2) ?
What's the upscaling mode you are using?
In the node settings are you using 'default' device? And if so, what GPU do you have?
Have you tried upscaling a low res image (something like 256x256) and see if it works within reasonable time?
Have you checked the ComfyUI's console for warnings? If something went wrong then the node might have printed a warning there.

**Comment by RaySteve312** [comment]
single;827*846;V2;Ultra sharp;cpu;no;no
yes,updated; no comfyui update and after updated still not working;

found out. all about the config,I updated the config.json yesterday. I delete it and now it works again!

Thank a lot for your support! love your node

**Comment by GreenLandisaLie** [comment]
You were probably getting a warning about the config file (in the console) and you missed it. 
Also if you are running it on the CPU then it is normal for it to be very slow but at least it works.
Glad its working now.
