### ISSUE TITLE
Upscaller parameter 2X | 4X etc...

### ISSUE THREAD

**Issue by kakachiex2** [GreenLandisaLie/AuraSR-ComfyUI#3]
Were is the upscaler parameter option like 2x, 4x, 15%, 25% etc...

**Comment by kakachiex2** [comment]
Check this link this guy made a good working one it can help to improve your node and its possible to add upscaling parameter
https://github.com/zsxkib/cog-aura-sr?tab=readme-ov-file#things-to-know-%EF%B8%8F

**Comment by GreenLandisaLie** [comment]
My bad. Just assumed the upscaler only worked well when upscaling to 4x because I read somewhere the model was trained for that ratio. I'll add that feature right away.

**Comment by GreenLandisaLie** [comment]
After looking into that repo's code I've noticed that it is not actually using AuraSR to upscale accordingly to the given scale_factor. Instead, it upscales with AuraSR by 4 - like normal - then uses PIL native .resize function to upscale further. This is no different than connecting the output of AuraSR to a basic (non-ai) upscaler node.

Code for reference:

```
        # Use the existing upscale_4x method
        upscaled_image = self.upscale_4x(image, max_batch_size)

        # Adjust the output based on the scale factor
        if scale_factor == 2:
            upscaled_image = upscaled_image.resize(
                (image.width * 2, image.height * 2), Image.BICUBIC
            )
        elif scale_factor in [8, 16, 32]:
            extra_scale = scale_factor // 4
            upscaled_image = upscaled_image.resize(
                (image.width * scale_factor, image.height * scale_factor), Image.BICUBIC
            )

        return upscaled_image
```

Since neither the native AuraSR code nor that one support a different scale factor - I won't be adding it either. Although I could - I'm sure the results wouldn't be good. This version of AuraSR (model) was trained exclusively with image pairs of 1:4 size ratios - so keep that in mind.
