### ISSUE TITLE
Very slow on MPS devices

### ISSUE THREAD

**Issue by ynie** [GreenLandisaLie/AuraSR-ComfyUI#5]
Hello, I have a MBP with M3 max, but it's still very slow. It has been running for 10mins and still running. I double check the device is MPS, does this behaves correct? Thanks

**Comment by GreenLandisaLie** [comment]
I cant debug because I only have an AMD GPU. 
I know for a fact that DirectML is not supported due to some internal operations involving negative dimensions. It is very likely that other devices like MPS are not supported either.
Additionally, it is possible that some operations are being defaulted back to the CPU (which can be extremely slow if trying to upscale already decently sized images).

Please try to open the '...\custom_nodes\AuraSR-ComfyUI\nodes.py' with a text editor and add a few lines around:
`upscaled_image = self.aura_sr.upscale_4x(image=image, max_batch_size=tile_batch_size)`
like so:
```
print("[AuraSR-ComfyUI] Start Inference...")
print(device)
upscaled_image = self.aura_sr.upscale_4x(image=image, max_batch_size=tile_batch_size)
print("[AuraSR-ComfyUI] Inference completed successfully.")
```
Then save the file and restart ComfyUI.
Try it again and make sure you give it a small image so it wouldn't take too much time to upscale (something like 256x256) then copy paste the log from your terminal so I can check it. 

If MPS is not supported I'll force offload to CPU like I'm doing with DirectML.

**Comment by alexgenovese** [comment]
it doesn't work on MPS

**Comment by GreenLandisaLie** [comment]
Closing this due to lack of info and lack of response.
I can't test on MPS because I don't have one. Either it works or it doesnt - and if it doesn't you can always try CPU mode - although it will obviously be extremely slow.

**Comment by alexgenovese** [comment]
@GreenLandisaLie, thank you for your response.

I'm trying to make it work somewhat; in case I come up with a solution, I'll create a pull request.
