### ISSUE TITLE
AuraSRv2 is out! Can it be added to this node pack?

### ISSUE THREAD

**Issue by EnragedAntelope** [GreenLandisaLie/AuraSR-ComfyUI#8]
https://huggingface.co/fal/AuraSR-v2

Thank you!

**Comment by GreenLandisaLie** [comment]
Yes it seems so. 

The model's underlying inference code and even its config file are exactly the same. Just dump it into the \models\Aura-SR folder and you should be good to go. 

Just a small note, they specifically use the '4x_overlapped_checkboard' mode (as named by this node) in their example as opposed to the regular '4x', so that is probably the one that works best but should be fine with the others as well. 

Its pretty much the same model, just either trained for longer or with a different dataset.

**Comment by GreenLandisaLie** [comment]
Honestly I don't know if V2 is an improvement. Somethings are better while others are much worse. But it works with this node so I'm closing this issue. Thanks for letting me know about this release.
